<h3 data-new = "true">New File</h3>
<div class = "fileContent">

<label><input class = "saveButton" type = "button" value = "Save"></label>
<label><input type = "button" value = "Save and Run"></label>
<br>

    <label><input type = "text" id = "fileName" data-config-name = "new file"></label>
<table class = 'envVars'>
    <tr data-type = "tableHead">
        <th>Переменные окружения</th>
        <th>Операции</th>
    </tr>
        <tr data-type = "tableContent" data-new-row = 'newEmptyRow'>
            <td data-type = 'editable' >
            </td>
            <td>
                <label><input type = "button" class = "delRowButton" value = "del row" id = "delButton" data-row-index = "0"></label>
                <label><input type = "button" class = "changeRowButton" value = "change row" id = "changeButton" data-row-index = "0"></label>
            </td>
        </tr>
</table>
<br>
<table class = 'cronCommands'>
    <tr data-type = "tableHead">
        <th colspan = "5">Расписание</th>
        <th>Владелец</th>
        <th>Команда</th>
        <th>Операции</th>
    </tr>
        <tr data-type = "tableContent" data-row-index = "0" data-new-row = 'newEmptyRow'>
            <td data-type = 'editable'>
            </td>
            <td data-type = 'editable'>
            </td>
            <td data-type = 'editable'>
            </td>
            <td data-type = 'editable'>
            </td>
            <td data-type = 'editable'>
            </td>
            <td data-type = 'editable'>
            </td>
            <td data-type = 'editable'>
            </td>
            <td>
                <label><input type = "button" class = "delRowButton" value = "del row" id = "delButton0" data-row-index = "0"></label>
                <label><input type = "button" class = "changeRowButton" value = "change row" id = "changeButton0" data-row-index = "0"></label>
            </td>
        </tr>
</table>
</div>
