<div id="environment">
    <label>
        <select id = "environmentList">
            <option data-id = '0' id = "emptyOption" selected = "true">Выберите ветку</option>
            <?php foreach ($envList as $key => $value): ?>
                <option data-id = '<?php echo $value['environmentId']; ?>' data-IP = '<?php echo $value['environmentIP']; ?>'>
                    <?php echo $value['environmentHostName']; ?>
                </option>;
            <?php endforeach ?>
        </select>
    </label>
</div>

<div id = "cronSources">
    <div id="accordionSource">
        <?php $n = 0; foreach($content as $file): ?>
            <h3><?php echo $file['sourceName']; ?></h3>
            <div class = "fileContent">
                <input type = "text" id = "sourceFileName" data-config-id = "<?php echo $file['configId']; ?>" hidden = "true" >
                <label><input type = "button" class = "addFullConfig" value = "Add" ></input></label>
                <br>
                <table>
                    <tr>
                        <th colspan = "5">Расписание</th>
                        <th>Владелец</th>
                        <th>Процесс</th>
                        <th>Команда</th>
                        <th>Добавить нужные</th>
                        <th>Операции</th>
                    </tr>
                    <?php foreach ($file['sourceContent'] as $index => $row): ?>
                        <tr>
                            <?php ++$n; foreach ($row as $rowElement): ?>
                                <td>
                                    <?php echo $rowElement; ?>
                                </td>
                            <?php endforeach ?>
                            <td><input class = "rowsGroup" type = "checkbox" data-row-index = "<?php echo $index; ?>"></input></td>
                            <td>
                                <label><input type = "button" class = "addRowButton" id = "addRowButton<?php echo $n; ?>" value = "add row"></input></label>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </table>
            </div>
        <?php endforeach ?>
    </div>
</div>