<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="utf-8">
	<title>Главная</title>
    <!--<link rel="stylesheet" type="text/css" href="./vendor/build/jquery.datetimepicker.min.css"/>-->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
    <link href="./css/style.css" rel="stylesheet">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <!--<script src="./vendor/build/jquery.datetimepicker.full.js"></script>-->
    <script src="./vendor/jquery-ui-1.12.0.custom/jquery-ui.js"></script>
    <script src="./js/script.js"></script>
</head>
<body>
<div id="container">

    <?php echo $content; ?>

    <div id = "cronConfig">

    </div>
</div>
</body>
</html>